import os
import numpy   as np
#import pyvista as pv
#import pyproj

def boresight_mesh_intersection(dem, geoPose, config):
    """Intersects the boresight-ray of the camera with the 3D triangular mesh

        :param mesh:           A mesh object read via the pyvista library
        :type mesh:            Pyvista mesh
        :param max_ray_length: The upper bound length of the camera rays (it is determined )
        :type max_ray_length:  _type_
    """
    # Calculate DEM offsets

    # EXECUTE THIS THE FIRST TIME
#    position_ref_ecef = geo_pose_ref.pos_geocsc
#    pos0 = np.mean(position_ref_ecef, axis=0)
#    config.set('AUTOGENERATED', 'offsetX', str(pos0[0]))
#    config.set('AUTOGENERATED', 'offsetY', str(pos0[1]))
#    config.set('AUTOGENERATED', 'offsetZ', str(pos0[2]))
    






    # calculate_intersection(dem, config)

    # Calculate the intersection of the boresight vector with the ground / DEM mesh
    n = dem.mesh.points.shape[0]
    m = 3



    


    n = self.rayDirectionsGlobal.shape[0]
    m = self.rayDirectionsGlobal.shape[1]

    self.points_ecef_crs  = np.zeros((n, m, 3), dtype=np.float64)
    self.normals_ecef_crs = np.zeros((n, m, 3), dtype=np.float64)



    # Calculate the intersection of the boresight vector with the ground


    pass
    
